--liquibase formatted sql

--changeset sburdiug:001_split_weather_raw dbms:postgresql runInTransaction:true
--preconditions onFail:HALT onError:HALT
--precondition-table-exists table:weather_raw

CREATE TABLE IF NOT EXISTS weather_record (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country         TEXT NOT NULL,
    location_name   TEXT NOT NULL,
    last_updated    TIMESTAMP NOT NULL,
    temperature_celsius DOUBLE PRECISION NOT NULL,
    wind_degree     INTEGER NOT NULL,
    wind_kph        DOUBLE PRECISION NOT NULL,
    wind_direction  wind_direction_enum NOT NULL

);

CREATE TABLE IF NOT EXISTS astronomy_info (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_record_id   INTEGER NOT NULL UNIQUE,
    sunrise             TIME NOT NULL,
    sunset              TIME NOT NULL,
    moonrise            TIME NULL,
    moonset             TIME NULL,
    moon_phase          TEXT NOT NULL,
    moon_illumination   INTEGER NOT NULL,
    CONSTRAINT fk_astronomy_info_weather_record
        FOREIGN KEY (weather_record_id)
        REFERENCES weather_record(id)
        ON DELETE CASCADE
);

INSERT INTO weather_record (
    id,
    country,
    location_name,
    last_updated,
    temperature_celsius,
    wind_degree,
    wind_kph,
    wind_direction
)
SELECT
    wr.id,
    wr.country,
    wr.location_name,
    wr.last_updated,
    wr.temperature_celsius,
    wr.wind_degree,
    wr.wind_kph,
    wr.wind_direction
FROM weather_raw wr
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('weather_record', 'id'),
    COALESCE((SELECT MAX(id) FROM weather_record), 1),
    true
);

INSERT INTO astronomy_info (
    weather_record_id,
    sunrise,
    sunset,
    moonrise,
    moonset,
    moon_phase,
    moon_illumination
)
SELECT
    wr.id,
    wr.sunrise,
    wr.sunset,
    wr.moonrise,
    wr.moonset,
    wr.moon_phase,
    wr.moon_illumination
FROM weather_raw wr
ON CONFLICT (weather_record_id) DO NOTHING;

--rollback DROP TABLE IF EXISTS astronomy_info;
--rollback DROP TABLE IF EXISTS weather_record;
